spring.application.name=mondash

spring.datasource.url=jdbc:postgresql://localhost:35432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# === Elasticsearch Configuration ===
spring.elasticsearch.uris=https://es01:9200
spring.elasticsearch.username=elastic
spring.elasticsearch.password=password

spring.ssl.bundle.pem.elasticsearch-ca.truststore.certificate=classpath:ca.crt
spring.elasticsearch.restclient.ssl.bundle=elasticsearch-ca

# === Index settings ===
spring.data.elasticsearch.repositories.enabled=true

spring.mustache.suffix=.html
