spring.application.name=mondash

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

server.port=8080
#spring.liquibase.enabled=true

# === Elasticsearch Configuration ===
spring.elasticsearch.uris=https://elastic.example.com:9200
spring.elasticsearch.username=elastic
spring.elasticsearch.password=elastic

spring.ssl.bundle.pem.elasticsearch-ca.truststore.certificate=classpath:ca.crt
spring.ssl.bundle.pem.matrix.truststore.certificate=classpath:matrix-ca.crt
spring.elasticsearch.restclient.ssl.bundle=elasticsearch-ca

# === Index settings ===
spring.data.elasticsearch.repositories.enabled=true

spring.mustache.suffix=.html

app.notification.ssl.bundle=matrix
app.notification.matrix.url=https://matrix.example.com
app.notification.matrix.room=room-id
app.notification.matrix.token=Bearer token
app.gitlab.token=glptt-token
app.gitlab.jobUrl=https://gitlab.example.com/api/v4/projects/1234/trigger/pipeline
